# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/si/code/gtest

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/si/code/gtest

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/si/code/gtest/CMakeFiles /home/si/code/gtest/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/si/code/gtest/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Main

# Build rule for target.
Main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Main
.PHONY : Main

# fast build rule for target.
Main/fast:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/build
.PHONY : Main/fast

battle.o: battle.cc.o
.PHONY : battle.o

# target to build an object file
battle.cc.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/battle.cc.o
.PHONY : battle.cc.o

battle.i: battle.cc.i
.PHONY : battle.i

# target to preprocess a source file
battle.cc.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/battle.cc.i
.PHONY : battle.cc.i

battle.s: battle.cc.s
.PHONY : battle.s

# target to generate assembly for a file
battle.cc.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/battle.cc.s
.PHONY : battle.cc.s

battle_rand.o: battle_rand.cc.o
.PHONY : battle_rand.o

# target to build an object file
battle_rand.cc.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/battle_rand.cc.o
.PHONY : battle_rand.cc.o

battle_rand.i: battle_rand.cc.i
.PHONY : battle_rand.i

# target to preprocess a source file
battle_rand.cc.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/battle_rand.cc.i
.PHONY : battle_rand.cc.i

battle_rand.s: battle_rand.cc.s
.PHONY : battle_rand.s

# target to generate assembly for a file
battle_rand.cc.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/battle_rand.cc.s
.PHONY : battle_rand.cc.s

character.o: character.cc.o
.PHONY : character.o

# target to build an object file
character.cc.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/character.cc.o
.PHONY : character.cc.o

character.i: character.cc.i
.PHONY : character.i

# target to preprocess a source file
character.cc.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/character.cc.i
.PHONY : character.cc.i

character.s: character.cc.s
.PHONY : character.s

# target to generate assembly for a file
character.cc.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/character.cc.s
.PHONY : character.cc.s

enemy.o: enemy.cc.o
.PHONY : enemy.o

# target to build an object file
enemy.cc.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/enemy.cc.o
.PHONY : enemy.cc.o

enemy.i: enemy.cc.i
.PHONY : enemy.i

# target to preprocess a source file
enemy.cc.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/enemy.cc.i
.PHONY : enemy.cc.i

enemy.s: enemy.cc.s
.PHONY : enemy.s

# target to generate assembly for a file
enemy.cc.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/enemy.cc.s
.PHONY : enemy.cc.s

main.o: main.cc.o
.PHONY : main.o

# target to build an object file
main.cc.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/main.cc.o
.PHONY : main.cc.o

main.i: main.cc.i
.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s
.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/main.cc.s
.PHONY : main.cc.s

myfunc.o: myfunc.cc.o
.PHONY : myfunc.o

# target to build an object file
myfunc.cc.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/myfunc.cc.o
.PHONY : myfunc.cc.o

myfunc.i: myfunc.cc.i
.PHONY : myfunc.i

# target to preprocess a source file
myfunc.cc.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/myfunc.cc.i
.PHONY : myfunc.cc.i

myfunc.s: myfunc.cc.s
.PHONY : myfunc.s

# target to generate assembly for a file
myfunc.cc.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/myfunc.cc.s
.PHONY : myfunc.cc.s

player.o: player.cc.o
.PHONY : player.o

# target to build an object file
player.cc.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/player.cc.o
.PHONY : player.cc.o

player.i: player.cc.i
.PHONY : player.i

# target to preprocess a source file
player.cc.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/player.cc.i
.PHONY : player.cc.i

player.s: player.cc.s
.PHONY : player.s

# target to generate assembly for a file
player.cc.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/player.cc.s
.PHONY : player.cc.s

ship.o: ship.cc.o
.PHONY : ship.o

# target to build an object file
ship.cc.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/ship.cc.o
.PHONY : ship.cc.o

ship.i: ship.cc.i
.PHONY : ship.i

# target to preprocess a source file
ship.cc.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/ship.cc.i
.PHONY : ship.cc.i

ship.s: ship.cc.s
.PHONY : ship.s

# target to generate assembly for a file
ship.cc.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/ship.cc.s
.PHONY : ship.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Main"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... battle.o"
	@echo "... battle.i"
	@echo "... battle.s"
	@echo "... battle_rand.o"
	@echo "... battle_rand.i"
	@echo "... battle_rand.s"
	@echo "... character.o"
	@echo "... character.i"
	@echo "... character.s"
	@echo "... enemy.o"
	@echo "... enemy.i"
	@echo "... enemy.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... myfunc.o"
	@echo "... myfunc.i"
	@echo "... myfunc.s"
	@echo "... player.o"
	@echo "... player.i"
	@echo "... player.s"
	@echo "... ship.o"
	@echo "... ship.i"
	@echo "... ship.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

